{
    "name": "Payment Methods Tracking",
    "version": "saas~16.4.3.3.0",
    "description": "Payment Methods Tracking",
    "summary": "Add the ability to track money flow when moving from stage to stage",
    "category": "External",
    "author": "VEGANET",
    "website": "https://www.vegagroup.com.tn",
    "license": "Other proprietary",
    "depends": [
        "base",
        "account",
        "account_batch_payment",
        "v__payment_methods",
        "v__payment_replace",
        "v__withholding_taxes",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/core/account_journal.xml",
        "views/core/account_payment.xml",
        "views/core/account_batch_payment.xml",
        "views/payment_method_line_stage.xml",
        "views/core/res_config_settings.xml",
        "wizards/next_stage_payment_wiz.xml",
        "wizards/regularize_by_certificate_wiz.xml",
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
    "sequence": 1,
}
