{
    "name": "Sale Enhancement",
    "version": "saas~16.4.1.5.9",
    "description": "Sale Enhancement",
    "category": "External",
    "author": "VegaNET",
    "website": "https://vegagroup.com.tn",
    "license": "Other proprietary",
    "depends": ["base", "contacts", "sale_management", "product", "sale"],
    "data": [
        "views/core/res_partner.xml",
        "views/core/sale_order.xml",
        "views/core/product_packaging_views.xml",
        "views/core/res_config_settings.xml",
        "wizards/account_move_comparison_wizard_view.xml",
        "wizards/account_move_comment_wizard_view.xml",
        "security/ir.model.access.csv",
        "report/export_order_simulation.xml",
        "report/customer_comparison_simulation.xml",
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
    "sequence": 1,
}
