{
    "name": "MRP Product Line",
    "version": "saas~16.4.1.1.5",
    "description": "MRP routing Enhancement",
    "summary": "Enhance MRP routing",
    "category": "External",
    "author": "VEAGANET",
    "website": "https://vegagroup.com.tn",
    "license": "Other proprietary",
    "depends": [
        "base",
        "mail",
        "product",
        "mrp",
        "quality",
        "quality_control",
        "v__message_service",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "views/mrp_routing.xml",
        "views/mrp_bom.xml",
        "views/mrp_routing_workcenter.xml",
        "views/product_template.xml",
    ],
    # 'demo': ['Demo'],
    "application": False,
    "auto_install": False,
    "installable": True,
    "sequence": 1,
}
