{
    "name": "Withholding Taxes",
    "version": "saas~16.4.3.9.1",
    "description": "Withholding Taxes",
    "summary": "Add a new payment method as a withholding taxes",
    "category": "External",
    "author": "VEGANET",
    "website": "https://www.vegagroup.com.tn",
    "license": "Other proprietary",
    "depends": ["base", "account", "v__payment_methods"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "report/withholding_certificate.xml",
        "views/core/account_payment.xml",
        "views/withholding_tax.xml",
        "wizards/core/account_payment_register.xml",
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
    "sequence": 1,
    "post_load": "post_load",
}
