{
    "name": "Stock Enhancement",
    "version": "saas~16.4.1.1.5",
    "description": "Stock Enhancement",
    "category": "External",
    "author": "VegaNET",
    "website": "https://vegagroup.com.tn",
    "license": "Other proprietary",
    "depends": ["base", "stock", "fleet", "sale_enhancement", "mail"],
    "data": [
        "views/stock_picking_views.xml",
        "views/product_template_views.xml",
        "views/product_product_views.xml",
        "report/stock_picking_label_report.xml",
        "views/stock_package_type_views.xml",
        "views/stock_container_views.xml",
        "views/stock_verification_views.xml",
        "report/inventory_product_template.xml",
        "report/ir_actions_report.xml",
        "security/ir.model.access.csv",
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
    "sequence": 1,
}
