{
    "name": "Merchandiser Management",
    "version": "saas~16.4.1.2.0",
    "description": "Merchandiser Management",
    "category": "External",
    "author": "VegaNet",
    "website": "https://vegagroup.com.tn",
    "license": "Other proprietary",
    "depends": ["base", "product", "planning", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/assortment_views.xml",
        "views/merchandise_planning_views.xml",
        "views/res_partner_store_views.xml",
        "views/core/product_template.xml",
        "views/core/product_views.xml",
        "views/core/planning_slot_views.xml",
        "views/core/res_partner.xml",
        "report/merchandiser_report.xml",
        "report/report_merchandise_planning.xml",
        "wizards/assortment_wizard_views.xml",
        "wizards/cancellation_reason_wizard_views.xml",
        "wizards/merchandiser_report_wizard_views.xml",
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
    "sequence": 1,
}
