{
    "name": "Product Variant Solo",
    "version": "saas~16.4.1.0.0",
    "description": "Product Variant Solo",
    "summary": "Show Product variant even if we have only one variant",
    "category": "External",
    "author": "VegaNET",
    "website": "https://vegagroup.com.tn",
    "license": "LGPL-3",
    "depends": ["base", "stock"],
    # 'data': ['Data'],
    # 'demo': ['Demo'],
    "application": False,
    "auto_install": False,
    "installable": True,
    "sequence": 1,
    # 'pre_init_hook': 'function_name',
    # 'post_init_hook': 'function_name',
    # 'uninstall_hook': 'function_name',
}
