{
    "name": "Leave Credit",
    "version": "saas~16.4.1.0.0",
    "category": "Human Resources",
    "website": "",
    "author": "",
    "license": "AGPL-3",
    "installable": True,
    "application": False,
    "summary": "Enable leave credit requests beyond allocations.",
    "depends": ["hr_holidays", "hr_payroll"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/cnss_declaration_views.xml",
        "views/hr_payroll_report_wizard.xml",
        "views/hr_salary_rule_views.xml",
        "views/hr_payroll_structure_view.xml",
        "views/hr_leave_type_views.xml",
        "views/report_payroll_payment_order.xml",
    ],
    "auto_install": False,
    "sequence": 1,
}
